export interface Movies {
    Title: string,
    Year: number,
    Rated: string,
    Released: string,
    Runtime: string,
    Genre: string,
    Director: string,
    Writer: string,
    Actors: string,
    Plot: string,
    Language: string,
    Country: string,
    Awards: string,
    Poster: string,
    Ratings: string[],
    Type: string,
    BoxOffice: string,
    Production: string,
    Response: boolean,
    imdbID: string,
    imdbRating: string,
}
//något mer?